### ISSUE TITLE
Fit module is not documented?

### ISSUE THREAD

**Issue by multimeric** [felix-clark/ndarray-glm#18]
It seems that the `Fit` struct returned by the `fit()` method is not documented, [for example](https://docs.rs/ndarray-glm/0.0.9/ndarray_glm/model/struct.Model.html#method.fit). Indeed it seems that the `fit` module that it belongs to is also not included in the list of modules in the documentation. Is there any way you can export either the struct in the prelude or the module itself so that it's documented. There's a chance that it's not possible to use the struct in type definitions either for the same reason, certainly my autocomplete doesn't find it.

**Comment by felix-clark** [comment]
Indeed, given that the user is obviously meant to interact with the `Fit` result directly I can't think of any reason why this should have been private in the first place -- probably just an oversight. The documentation also certainly should be public (the quality of that documentation is... another issue).

I've exported the `Fit` object directly in f66909d, as opposed to making the module public, since I don't think users should have to manage the namespace here. Feel free to try out the 0.0.10 branch (unpublished right now - you'll have to use the git syntax in `Cargo.toml`) and check that the behavior of everything works as you'd expect.

**Comment by multimeric** [comment]
The main thing I'm after is actually the documentation page which I guess won't come until it's actually published. But it's good to know that this is coming!

**Comment by felix-clark** [comment]
Closing as this should be fixed in 0.0.10.
