### ISSUE TITLE
Estimate the variance sigma2

### ISSUE THREAD

**Issue by multimeric** [felix-clark/ndarray-glm#20]
It seems that OLS regression is the type that has been implemented, so makes the assumption of a fixed sigma squared: the scalar variance of the errors and also y. How can this be extracted from the fit object? Is it the same as the `dispersion()` function? Calling this parameter "dispersion" is a bit unfamiliar to me.

**Comment by felix-clark** [comment]
Yes, `dispersion()` returns the dispersion parameter (often denoted as phi) which for a Gaussian response function is equal to sigma^2. In a constant linear model with no covariates, this should be equal to the unbiased sample variance. I believe it is only an approximation for non-linear models, however.

I worry that exposing another function simply called `variance()` could lead to confusion, since the term "variance" is pretty overloaded in the GLM context. Maybe this is primarily a documentation issue. I'm open to more suggestions here.

**Comment by multimeric** [comment]
I think if you just said what you just said in the documentation for `dispersion()` it would be quite clear. In particular:
> In a constant linear model with no covariates, this should be equal to the unbiased sample variance. I believe it is only an approximation for non-linear models, however.

**Comment by felix-clark** [comment]
The documentation for `dispersion()` has been re-written with more detail; hopefully this is enough for now.
