### ISSUE TITLE
R^2 / coefficient of multiple correlation

### ISSUE THREAD

**Issue by multimeric** [felix-clark/ndarray-glm#21]
Would also be nice for this to be implemented.

**Comment by felix-clark** [comment]
I hadn't implemented this yet because I think a generalized R^2 for an arbitrary GLM involves some subtleties, but users doing simple OLS (i.e. `Linear`) regression will expect this. The residual sum of squares might also be nice for OLS. I think I should be able to specialize these for the `Linear` case for now.

**Comment by multimeric** [comment]
Yes even just implementing it for Linear would be fantastic. That's all I'm doing at the moment.

**Comment by felix-clark** [comment]
Implemented `r_sq()` and `residual_sum_sq()` for linear fits in 65402d3. Feel free to test it out on the 0.0.10 branch and send back any more comments.

**Comment by multimeric** [comment]
Great, will do!

**Comment by multimeric** [comment]
This looks like it's working brilliantly! It even fixed a bug I was having due to my wrong calculation of degrees of freedom.

Incidentally, looking at the code I can maybe see some merit to say caching the residuals since it's recalculated by so many other functions (dispersion, pearson residuals etc).

**Comment by felix-clark** [comment]
I'll move discussion of caching in general to #25 and close this issue.

Thanks for all your help in identifying pain points!
